name: Build and Test

on:
  push:
    branches:
      - master  # Altere para a branch principal do seu repositório

jobs:
  build:
    runs-on: self-hosted  # O runner que você configurou
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.1

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

